#!/bin/bash
source ./submodules/bootstrap/logging

#-----------
# Configurations
#-----------

NGINX_LAUNCHER_DIR=${NGINX_LAUNCHER_DIR-/var/local/nginx}
NGINX_INCLUDE_RELOAD=${NGINX_INCLUDE_RELOAD-true}
NGINX_INCLUDE_PHP=${NGINX_INCLUDE_PHP-true}
NGINX_INCLUDE_MYSQL=${NGINX_INCLUDE_MYSQL-true}
DOCKER_SUPPORT_LXC=${DOCKER_SUPPORT_LXC-false}

export NGINX_APPS_DIR=${NGINX_APPS_DIR-/var/local/apps}
export NGINX_SITES_ENABLED_DIR=${NGINX_SITES_ENABLED_DIR-/etc/nginx/sites-enabled}
export NGINX_SITES_AVAILABLE_DIR=${NGINX_SITES_AVAILABLE_DIR-/etc/nginx/sites-available}
export NGINX_LOG_DIR=${NGINX_LOG_DIR-/var/log/nginx}
export NGINX_HTTP_PORT=${NGINX_HTTP_PORT-80}
export NGINX_SSL_PORT=${NGINX_SSL_PORT-443}

#-----------
# Install Script
#-----------

notify "Install nginx..."

mkdir -p $NGINX_LAUNCHER_DIR/files
mkdir -p $NGINX_LAUNCHER_DIR/startup.d
mkdir -p $NGINX_SITES_ENABLED_DIR $NGINX_SITES_AVAILABLE_DIR

chown -R www-data:www-data $NGINX_SITES_ENABLED_DIR
chown -R www-data:www-data $NGINX_SITES_AVAILABLE_DIR

cp ./submodules/nginx/files/nginx.dockerfile $NGINX_LAUNCHER_DIR/Dockerfile

cp ./submodules/nginx/files/php5_fpm $NGINX_LAUNCHER_DIR/files/php5_fpm

if [[ ! -e $NGINX_LAUNCHER_DIR/files/do_nothing ]]; then
  printf '#!/bin/bash\n# Do nothing\n' > $NGINX_LAUNCHER_DIR/files/do_nothing
  chmod 755 $NGINX_LAUNCHER_DIR/files/do_nothing
fi

if [[ "$NGINX_INCLUDE_PHP" = true ]]; then
  notify "  -- enabling php"
  sed -i 's|# @PHP_INSTALL@|cat ./submodules/nginx/files/php_partial.dockerfile|e' $NGINX_LAUNCHER_DIR/Dockerfile
fi

if [[ "$NGINX_INCLUDE_MYSQL" = true ]]; then
  notify "  -- enabling mysql"
  sed -i 's|# @MYSQL_INSTALL@|cat ./submodules/nginx/files/mysql_partial.dockerfile|e' $NGINX_LAUNCHER_DIR/Dockerfile
fi

if [[ "$NGINX_INCLUDE_RELOAD" = true ]]; then
  cp ./submodules/nginx/files/nginx_touch $NGINX_LAUNCHER_DIR/files/nginx_touch
  cp ./submodules/nginx/files/touchandgo $NGINX_LAUNCHER_DIR/files/touchandgo
  cp ./submodules/nginx/files/nginx_reload $NGINX_LAUNCHER_DIR/files/nginx_reload
  sed -i 's|# @RELOAD_INSTALL@|cat ./submodules/nginx/files/reload_partial.dockerfile|e' $NGINX_LAUNCHER_DIR/Dockerfile
fi

LAUNCHER_DIR=$NGINX_LAUNCHER_DIR NAME=nginx ./submodules/docker/build

if [[ "$DOCKER_SUPPORT_LXC" == true ]]; then
  notify "  -- enabling LXC support"
  cp ./submodules/nginx/files/console $NGINX_LAUNCHER_DIR/console
  chmod 755 $NGINX_LAUNCHER_DIR/console
fi

NAME=nginx DIR=$NGINX_LAUNCHER_DIR \
  START=./submodules/nginx/files/_start \
  DEBUG=./submodules/nginx/files/_debug \
  ./submodules/docker/helpers

notify "DONE, Install nginx."