#!/bin/bash

#-----------
# Configurations
#-----------

NGINX_SITES_ENABLED_DIR=${NGINX_SITES_ENABLED_DIR-/etc/nginx/sites-enabled}
NGINX_SITES_AVAILABLE_DIR=${NGINX_SITES_AVAILABLE_DIR-/etc/nginx/sites-available}
NGINX_LOG_DIR=${NGINX_LOG_DIR-/var/log/nginx}
NGINX_HTTP_PORT=${NGINX_HTTP_PORT-80}
NGINX_SSL_PORT=${NGINX_SSL_PORT-443}
NGINX_APPS_DIR=${NGINX_APPS_DIR-/var/apps}

NGINX_INCLUDE_PHP=${NGINX_INCLUDE_PHP-true}
NGINX_INCLUDE_MYSQL=${NGINX_INCLUDE_MYSQL-true}

DOCKER_SUPPORT_LXC=${DOCKER_SUPPORT_LXC-false}

#-----------
# Install Script
#-----------

mkdir -p /var/apps/nginx
mkdir -p /var/apps/nginx/startup.d
mkdir -p $NGINX_SITES_ENABLED_DIR $NGINX_SITES_AVAILABLE_DIR

chown -R www-data:www-data $NGINX_SITES_ENABLED_DIR
chown -R www-data:www-data $NGINX_SITES_AVAILABLE_DIR
cp ./submodules/nginx/files/nginx.dockerfile /var/apps/nginx/Dockerfile

if [[ "$NGINX_INCLUDE_PHP" = true ]]; then
  sed -i 's|# @PHP_INSTALL@|cat ./submodules/nginx/files/php_partial.dockerfile|e' /var/apps/nginx/Dockerfile
  printf '#!/bin/bash\n/etc/init.d/php5-fpm restart\n' > /var/apps/nginx/startup.d/php5_fpm
  chmod 755 /var/apps/nginx/startup.d/php5_fpm
else
  printf '#!/bin/bash\n# Do nothing\n' > /var/apps/nginx/startup.d/empty
  chmod 755 /var/apps/nginx/startup.d/empty
  rm -f /var/apps/nginx/startup.d/php5_fpm
fi

if [[ "$NGINX_INCLUDE_MYSQL" = true ]]; then
  sed -i 's|# @MYSQL_INSTALL@|cat ./submodules/nginx/files/mysql_partial.dockerfile|e' /var/apps/nginx/Dockerfile
fi

(cd /var/apps/nginx && docker build -t nginx .)

if [[ "$DOCKER_SUPPORT_LXC" == true ]]; then
  cp ./submodules/nginx/files/console /var/apps/nginx/console
  chmod 755 /var/apps/nginx/console
fi

echo "docker run -i -p $NGINX_HTTP_PORT:80 -p $NGINX_SSL_PORT:443 -v $NGINX_APPS_DIR:/var/apps -v $NGINX_SITES_ENABLED_DIR:/etc/nginx/sites-enabled -v $NGINX_SITES_AVAILABLE_DIR:/etc/nginx/sites-available -v $NGINX_LOG_DIR:/var/log/nginx -t nginx /bin/bash" > /var/apps/nginx/debug
echo "docker run -d -p $NGINX_HTTP_PORT:80 -p $NGINX_SSL_PORT:443 -v $NGINX_APPS_DIR:/var/apps -v $NGINX_SITES_ENABLED_DIR:/etc/nginx/sites-enabled -v $NGINX_SITES_AVAILABLE_DIR:/etc/nginx/sites-available -v $NGINX_LOG_DIR:/var/log/nginx nginx" > /var/apps/nginx/start
echo 'docker stop $(docker ps -aq --no-trunc)' > /var/apps/nginx/stop

cp ./submodules/nginx/files/idempot /var/apps/nginx/idempot

chmod 755 /var/apps/nginx/start
chmod 755 /var/apps/nginx/idempot
chmod 755 /var/apps/nginx/debug
chmod 755 /var/apps/nginx/stop
