#!/bin/bash

#-----------
# Configurations
#-----------

NGINX_SITES_ENABLED_DIR=${NGINX_SITES_ENABLED_DIR-/etc/nginx/sites-enabled}
NGINX_SITES_AVAILABLE_DIR=${NGINX_SITES_AVAILABLE_DIR-/etc/nginx/sites-available}
NGINX_LOG_DIR=${NGINX_LOG_DIR-/var/log/nginx}
NGINX_HTTP_PORT=${NGINX_HTTP_PORT-80}
NGINX_SSL_PORT=${NGINX_SSL_PORT-443}
NGINX_APPS_DIR=${NGINX_APPS_DIR-/var/local/apps}

NGINX_INCLUDE_PHP=${NGINX_INCLUDE_PHP-true}
NGINX_INCLUDE_MYSQL=${NGINX_INCLUDE_MYSQL-true}

DOCKER_SUPPORT_LXC=${DOCKER_SUPPORT_LXC-false}

#-----------
# Install Script
#-----------

mkdir -p /var/local/nginx
mkdir -p /var/local/nginx/startup.d
mkdir -p $NGINX_SITES_ENABLED_DIR $NGINX_SITES_AVAILABLE_DIR

chown -R www-data:www-data $NGINX_SITES_ENABLED_DIR
chown -R www-data:www-data $NGINX_SITES_AVAILABLE_DIR
cp ./submodules/nginx/files/nginx.dockerfile /var/local/nginx/Dockerfile

if [[ "$NGINX_INCLUDE_PHP" = true ]]; then
  sed -i 's|# @PHP_INSTALL@|cat ./submodules/nginx/files/php_partial.dockerfile|e' /var/local/nginx/Dockerfile
  printf '#!/bin/bash\n/etc/init.d/php5-fpm restart\n' > /var/local/nginx/startup.d/php5_fpm
  chmod 755 /var/local/nginx/startup.d/php5_fpm
else
  printf '#!/bin/bash\n# Do nothing\n' > /var/local/nginx/startup.d/empty
  chmod 755 /var/local/nginx/startup.d/empty
  rm -f /var/local/nginx/startup.d/php5_fpm
fi

if [[ "$NGINX_INCLUDE_MYSQL" = true ]]; then
  sed -i 's|# @MYSQL_INSTALL@|cat ./submodules/nginx/files/mysql_partial.dockerfile|e' /var/local/nginx/Dockerfile
fi

(cd /var/local/nginx && docker build -t nginx .)

if [[ "$DOCKER_SUPPORT_LXC" == true ]]; then
  cp ./submodules/nginx/files/console /var/local/nginx/console
  chmod 755 /var/local/nginx/console
fi

printf "%b" "#!/bin/bash
docker run -i -t \\
  -p 9997:80 \\
  -p 9996:443 \\
  -v $NGINX_APPS_DIR:/var/local/apps \\
  -v $NGINX_SITES_ENABLED_DIR:/etc/nginx/sites-enabled \\
  -v $NGINX_SITES_AVAILABLE_DIR:/etc/nginx/sites-available \\
  -v $NGINX_LOG_DIR:/var/log/nginx \\
  nginx /bin/bash" > /var/local/nginx/debug

printf "%b" "#!/bin/bash
docker rm nginx > /dev/num
docker run -d -t \\
  -p $NGINX_HTTP_PORT:80 \\
  -p $NGINX_SSL_PORT:443 \\
  -v $NGINX_APPS_DIR:/var/local/apps \\
  -v $NGINX_SITES_ENABLED_DIR:/etc/nginx/sites-enabled \\
  -v $NGINX_SITES_AVAILABLE_DIR:/etc/nginx/sites-available \\
  -v $NGINX_LOG_DIR:/var/log/nginx \\
  --name nginx \\
  nginx" > /var/local/nginx/start

NAME=nginx DIR=/var/local/nginx ./submodules/docker/idempot
NAME=nginx DIR=/var/local/nginx ./submodules/docker/stop

chmod 755 /var/local/nginx/start
chmod 755 /var/local/nginx/debug
