#!/bin/bash
./submodules/docker/install
./submodules/nginx/install

cp ./submodules/nginx/files/helloworld_nginx_conf /etc/nginx/sites-enabled/helloworld
mkdir -p /var/apps/helloworld
echo "HELLO WORLD" > /var/apps/helloworld/index.html
echo "<?php phpinfo(); ?>" > /var/apps/helloworld/index.php
