#!/bin/bash
HOST=postgres.local
IP=$PSQLDB_PORT_5432_TCP_ADDR

if [[ "`cat /etc/hosts | grep $HOST`" == '' ]]; then
  echo "  -- Adding $HOST ($IP) to /etc/hosts"
  echo "$IP $HOST" >> /etc/hosts
else
  echo "  -- Updating $HOST ($IP) in /etc/hosts"
  sed -i "s|.*$HOST|$IP $HOST|g" /etc/hosts
fi
